name: CI

on:
  push:
    branches:
      - "staging" # pastikan ini adalah nama branch yang benar

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          IPAY_API_KEY: ${{ secrets.IPAY_API_KEY }}
          IPAY_VA: ${{ secrets.IPAY_VA }}
          IPAY_URL: ${{ secrets.IPAY_URL }}
        run: |
          echo "Environment variables set!"
      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pgapi_backend:latest

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Stopping and removing previous container..."
            docker stop ${{ vars.CONTAINER_NAME }} || true && docker rm ${{ vars.CONTAINER_NAME }} || true
            echo "Pulling the latest image..."
            docker pull ${{ vars.IMAGE_NAME }}:latest
            echo "Running the container..."
            docker run -d \
              -p 1213:1213 \
              --name ${{ vars.CONTAINER_NAME }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e FRONTEND_URL=${{ vars.FRONTEND_URL }} \
              -e IPAY_API_KEY=${{ secrets.IPAY_API_KEY }} \
              -e IPAY_VA=${{ secrets.IPAY_VA }} \
              -e IPAY_URL=${{ secrets.IPAY_URL }} \
              ${{ vars.IMAGE_NAME }}:latest
